apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/my-app/devfile-sample@sha256:8a48da136c4171d7b524ce8236a907c136c4a28ea659d2f3e6099ca28f098d25
        name: my-nodejs
        resources: {}
status: {}
